(require 'color-theme)

;;;###autoload
(defun color-theme-gentooish ()
  "Mostly green and purple color theme"
  (interactive)
  (color-theme-install
   '(color-theme-gentooish
     ((foreground-color . "#c0c0c0")
      (background-color . "#171717")
      (border-color . "black")
      (cursor-color . "green")
      (background-mode . dark))
     (bold ((t (:foreground "white" :weight normal))))
     (font-lock-builtin-face ((t (:foreground "#c476f1"))))
     (font-lock-comment-face ((t (:foreground "grey30"))))
     (font-lock-function-name-face ((t (:foreground "#4cbbd1"))))
     (font-lock-keyword-face ((t (:foreground "#9a383a"))))
     (font-lock-string-face ((t (:background "#0f291a" :foreground "#5dff9e"))))
     (hi-blue ((((background dark)) (:background "grey20"))))
     (ido-first-match ((t (:background "#361d45" :foreground "#cf7dff" :weight bold))))
     (ido-only-match ((t (:background "#361d45" :foreground "#cf7dff" :weight bold))))
     (ido-subdir ((t (:foreground "#7dcfff"))))
     (linum ((t (:inherit shadow :background "grey12"))))
     (minibuffer-prompt ((t (:foreground "#863335"))))
     (highlight ((t (:background "#133622"))))
     (mode-line ((t (:background "#333333" :foreground "#ffffff" :box (:line-width -1 :color "#333333")))))
     (mode-line-highlight ((t (nil))))
     (mode-line-inactive ((default (:inherit mode-line)) (t (:foreground "#8b8b8b" :weight light))))
     (show-paren-match ((t (:background "#005500"))))
     (tool-bar ((default (:foreground "black")) (t (:background "grey75")))))))
(add-to-list 'color-themes '(color-theme-gentooish "Gentooish" "Brian Carper"))
